/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is a bootstrap stub generated by create-four-app.
// It will be regenerated by the TanStack Router Vite plugin on first `vite dev`.
// Do not edit manually — your changes will be overwritten.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";

declare module "@tanstack/router-core" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export const routeTree = rootRouteImport._addFileChildren([IndexRoute]);
