/* eslint-disable */
// This file is a bootstrap stub generated by create-four-app.
// It will be regenerated by the TanStack Start Vite plugin on first `vite dev`.
// Do not edit manually — your changes will be overwritten.

import type { Route as RootRouteType } from "./routes/__root";
import type { Route as IndexRouteType } from "./routes/index";
import type { Route as ApiHealthRouteType } from "./routes/api.health";

// Augment FileRoutesByPath so createFileRoute('/') and createFileRoute('/api/health')
// are typed before the Vite plugin regenerates this file.
declare module "@tanstack/router-core" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteType;
      parentRoute: typeof RootRouteType;
    };
    "/api/health": {
      id: "/api/health";
      path: "/api/health";
      fullPath: "/api/health";
      preLoaderRoute: typeof ApiHealthRouteType;
      parentRoute: typeof RootRouteType;
    };
  }
}

export {};
